import type { QTableColumn } from 'quasar';

export const frameListColumns: QTableColumn[] = [
  {
    name: '_index',
    label: '#',
    field: '_index',
    align: 'center',
    sortable: false,
    headerStyle: 'width: 48px',
    style: 'width: 48px',
  },
  {
    name: 'id',
    label: '帧ID',
    field: 'id',
    align: 'left',
    sortable: true,
    headerStyle: 'width: 140px',
    style: 'width: 140px',
  },
  {
    name: 'name',
    label: '名称',
    field: 'name',
    align: 'left',
    sortable: true,
  },
  {
    name: 'direction',
    label: '方向',
    field: 'direction',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 80px',
    style: 'width: 80px',
  },
  {
    name: 'fieldCount',
    label: '字段数',
    field: 'fieldCount',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 80px',
    style: 'width: 80px',
  },
  {
    name: 'frameType',
    label: '类型',
    field: 'frameType',
    align: 'left',
    sortable: true,
    headerStyle: 'width: 100px',
    style: 'width: 100px',
  },
  {
    name: 'isFavorite',
    label: '收藏',
    field: 'isFavorite',
    align: 'center',
    sortable: true,
    headerStyle: 'width: 56px',
    style: 'width: 56px',
  },
  {
    name: '_actions',
    label: '操作',
    field: '_actions',
    align: 'center',
    sortable: false,
    headerStyle: 'width: 160px',
    style: 'width: 160px',
  },
];
