import type { QTableColumn } from 'quasar';

export const frameFieldColumns: QTableColumn[] = [
	{
		name: 'name',
		label: '名称',
		field: 'name',
		align: 'left',
		sortable: false,
	},
	{
		name: 'dataType',
		label: '类型',
		field: 'dataType',
		align: 'center',
		sortable: false,
		headerStyle: 'width: 80px',
		style: 'width: 80px',
	},
	{
		name: 'length',
		label: '长度',
		field: 'length',
		align: 'center',
		sortable: false,
		headerStyle: 'width: 60px',
		style: 'width: 60px',
	},
	{
		name: 'dataParticipationType',
		label: '参与类型',
		field: 'dataParticipationType',
		align: 'center',
		sortable: false,
		headerStyle: 'width: 80px',
		style: 'width: 80px',
	},
	{
		name: 'inputType',
		label: '输入类型',
		field: 'inputType',
		align: 'center',
		sortable: false,
		headerStyle: 'width: 80px',
		style: 'width: 80px',
	},
	{
		name: '_actions',
		label: '操作',
		field: '_actions',
		align: 'center',
		sortable: false,
		headerStyle: 'width: 240px',
		style: 'width: 240px',
	},
];
